name: bus_router
description: "App to control the city's bus routes."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  test: ^1.24.9
  bloc_test: ^9.1.5
  equatable: ^2.0.5
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.5.3
  location: ^5.0.3
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
